apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/aknkya/helm-repo
      targetRevision: main
      path: myapp
      helm:
        valueFiles:
          - $values/values-dev.yaml
    - repoURL: https://github.com/aknkya/helm-config-
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {}